name: release

on:
  push:
  release:
    types:
      - published
  schedule:
    - cron: '45 5 * * *'

jobs:
  build:
    strategy:
      matrix:
        build_cmd:
        - ./build-latest.sh
      fail-fast: false
    runs-on: ubuntu-latest
    name: Builds new NetBox Docker Images
    env:
      GH_ACTION: enable
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Get Version of NetBox Docker
      run: |
        echo "::set-output name=version::$(cat VERSION)"
      shell: bash
    -
      id: docker-build
      name: Build the image with '${{ matrix.build_cmd }}'
      run: ${{ matrix.build_cmd }}
    -
      name: Test the image
      run: IMAGE="${FINAL_DOCKER_TAG}" ./test.sh
      if: steps.docker-build.outputs.skipped != 'true'

    # ghcr.io
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: steps.docker-build.outputs.skipped != 'true'
    -
      name: Build and push the image with '${{ matrix.build_cmd }}'
      run: ${{ matrix.build_cmd }} --push
      env:
        DOCKER_REGISTRY: ghcr.io
        DOCKER_ORG: netbox-community
      if: steps.docker-build.outputs.skipped != 'true'
